export const colors = [
  { party: "NO RESULT", color: "#FFFFFF" },
  { party: "INDEPENDENT", color: "#FFFEF0" },
    { party: "ANC", color: "#15616d" },
    { party: "DA", color: "#ff5c5c" },
    { party: "EFF", color: "#FCF6B1" },
    { party: "UDM", color: "#F7B32B" },
    { party: "ATM", color: "#2D1E2F" },
    { party: "VF PLUS", color: "#FCE3B0" },
    { party: "ACDP", color: "#B38FB7" },
    { party: "AIC", color: "#C0ECCD" },
    { party: "PAC", color: "#FF7D00" },
    { party: "COPE", color: "#78290F" },
    { party: "ATA", color: "#FFA047" },
    { party: "SRWP", color: "#FFE6C2" },
    { party: "GOOD", color: "#d9cfc1" },
    { party: "ASC", color: "#ECCB83" },
    { party: "ZACP", color: "#e8e2d9" },
    { party: "ALJAMA", color: "#806b4d" },
    { party: "BLF", color: "#9fb8d0" },
    { party: "SRWP", color: "#bbcddd" },
    { party: "IFP", color: "#446888" },
    { party: "NFP", color: "#eccb83" },
  ]