version: '3'
services:
  app:
    build:
      dockerfile: ./Dockerfile
    ports:
      - 7002:7002
    environment:
      - NODE_ENV=production
      - PORT=7002
      - HOST=0.0.0.0
      - REDIS_URL=redis://keydb:6379
    env_file:
      - ./.env
    restart: unless-stopped
    depends_on:
      - keydb
  keydb:
    image: eqalpha/keydb
    restart: unless-stopped
    volumes:
      - ./data:/data